import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.core.agent import run_agent
from app.routes.voice_routes import router as voice_router
from app.routes.data_routes import router as data_router

app = FastAPI()

# ✅ CORS: Allow all origins for the separate frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Change this to your frontend URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ API ROUTES
app.include_router(voice_router)
app.include_router(data_router)

@app.get("/chat")
def chat(q: str):
    response = run_agent(q)
    return {"response": response}

# ✅ STATIC ASSETS (Audio generated by TTS)
# Note: Ensure the backend directory contains the audio files or save them to a specific folder
app.mount("/audio", StaticFiles(directory="."), name="audio")

@app.get("/")
def root():
    return {"status": "Ather AI Backend is running"}